# Generated by Django 4.0.4 on 2022-05-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rental_name_reservation_checkin_reservation_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
