# Generated by Django 4.0.4 on 2022-05-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_reservation_user_reservation_rental_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkIn',
            field=models.DateTimeField(),
        ),
    ]
