# Generated by Django 4.0.4 on 2022-05-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_reservation_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkOut',
            field=models.DateTimeField(),
        ),
    ]
