# Generated by Django 4.0.4 on 2022-05-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_reservation_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='previous_reservation_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
