# Generated by Django 4.0.4 on 2022-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_reservation_previous_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkIn',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkOut',
            field=models.DateField(),
        ),
    ]
