# Generated by Django 4.0.4 on 2022-05-31 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_reservation_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='test',
        ),
    ]
